// <auto-generated />
using System;
using Clientes.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clientes.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910175544_CampoCodigoTelefone")]
    partial class CampoCodigoTelefone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clientes.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioInsercao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Clientes.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("CodigoCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CodigoTelefone")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoTipoTelefone")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operadora")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioInsercao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoCliente", "NumeroTelefone");

                    b.HasIndex("CodigoTipoTelefone");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Clientes.Domain.Entities.TipoTelefone", b =>
                {
                    b.Property<Guid>("CodigoTipoTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoTipoTelefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioInsercao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoTipoTelefone");

                    b.ToTable("TiposTelefone");

                    b.HasData(
                        new
                        {
                            CodigoTipoTelefone = new Guid("0e481610-8420-410f-b02b-3ea66b39d854"),
                            DataInsercao = new DateTime(2025, 9, 10, 17, 55, 43, 859, DateTimeKind.Utc).AddTicks(3974),
                            DescricaoTipoTelefone = "RESIDENCIAL",
                            UsuarioInsercao = "sistema"
                        },
                        new
                        {
                            CodigoTipoTelefone = new Guid("858dd8c5-921a-4a0b-aaeb-3293e4afcf05"),
                            DataInsercao = new DateTime(2025, 9, 10, 17, 55, 43, 859, DateTimeKind.Utc).AddTicks(3992),
                            DescricaoTipoTelefone = "COMERCIAL",
                            UsuarioInsercao = "sistema"
                        },
                        new
                        {
                            CodigoTipoTelefone = new Guid("fbe917e7-5d43-44cb-b375-e3cbe44e3d42"),
                            DataInsercao = new DateTime(2025, 9, 10, 17, 55, 43, 859, DateTimeKind.Utc).AddTicks(3995),
                            DescricaoTipoTelefone = "",
                            UsuarioInsercao = "sistema"
                        },
                        new
                        {
                            CodigoTipoTelefone = new Guid("1aaae748-3a5a-496e-8626-9692d277e1da"),
                            DataInsercao = new DateTime(2025, 9, 10, 17, 55, 43, 859, DateTimeKind.Utc).AddTicks(3997),
                            DescricaoTipoTelefone = "CELULAR",
                            UsuarioInsercao = "sistema"
                        });
                });

            modelBuilder.Entity("Clientes.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("Clientes.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Telefones")
                        .HasForeignKey("CodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clientes.Domain.Entities.TipoTelefone", "TipoTelefone")
                        .WithMany("Telefones")
                        .HasForeignKey("CodigoTipoTelefone")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoTelefone");
                });

            modelBuilder.Entity("Clientes.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Clientes.Domain.Entities.TipoTelefone", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
